services:
  admin-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: msdp-admin-dashboard-dev
    ports:
      - "4000:3000"  # Using centralized port allocation
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_ADMIN_SERVICE_URL=http://localhost:3005
      - NEXT_PUBLIC_API_GATEWAY_URL=http://localhost:3000
    volumes:
      # Source code hot reload (optimized)
      - ./src:/app/src:cached
      - ./package.json:/app/package.json:ro
      - ./next.config.ts:/app/next.config.ts:ro
      - ./tailwind.config.js:/app/tailwind.config.js:ro
      # Exclude node_modules and .next from host
      - admin_dashboard_node_modules:/app/node_modules
      - admin_dashboard_next:/app/.next
    networks:
      - msdp-admin-frontend-network
    restart: unless-stopped

volumes:
  admin_dashboard_node_modules:
    name: msdp_admin_dashboard_node_modules
  admin_dashboard_next:
    name: msdp_admin_dashboard_next

networks:
  msdp-admin-frontend-network:
    driver: bridge
    name: msdp-admin-frontend-network